utilitywarehouse/kafka-cluster-config

dev-merit/kafka-shared/otel.tf

No quota settings yet. Will add this after validating the integration between otel and shared kafka cluster with TLS works

Add topic and ACLs for otel

---

prod-aws/kafka-shared/backend.tf
prod-aws/kafka-shared/kafka-exporter.tf
prod-aws/kafka-shared/mirror-maker.tf
prod-aws/kafka-shared/otel.tf
prod-aws/kafka-shared/pdp-audit.tf
prod-aws/kafka-shared/provider.tf

- kafka-shared prod-aws: added config from merit
- kafka-shared prod-aws: updated otel topic & added mirror maker

PLA2-28: prod aws pubsub setup

---

dev-aws/kafka-shared/customer-billing-invoice-fulfillment.tf
dev-aws/kafka-shared/customer-billing/invoice-fulfillment/invoice-fulfillment.tf

This PR adds TF configuration to create a new Kafka topic and a producer on the new Kafka cluster using the module approach.

Adds TF configuration to create a Kafka topic and producer for invoice-fulfillment service

---

dev-aws/kafka-shared/customer-billing-invoice-fulfillment.tf

fix module ref

---

dev-aws/customer-billing/backend.tf
dev-aws/customer-billing/provider.tf
dev-aws/customer-billing/topics.tf

- Creates tf manifests for our new kafka cluster.

[BEX-481]: Create topics for new kafka cluster.

---

dev-aws/finance/direct-debits.tf
prod-aws/finance/direct_debits.tf

Related PR: https://github.com/utilitywarehouse/finance-mono/pull/519

feat(fin-924): Add new topic for the reconciliation scheduler events 

---

dev-aws/kafka-shared/pubsub-examples.tf

Using the TF modules -> the resources should stay the same

pubsub-examples: use the modules for resources.

---

prod-aws/kafka-shared/iam_identitydb.tf

Same change as [dev](https://github.com/utilitywarehouse/kafka-cluster-config/blob/main/dev-aws/kafka-shared/iam_identitydb.tf) but for prod

IAM identitydb topic in prod

---

dev-merit/kafka-shared/pubsub-examples.tf

This PR allows the es-topic-indexer ([to be deployed here](https://github.com/utilitywarehouse/kubernetes-manifests/pull/83872))read the pubsub examples
```diff
Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
+ create
+ resource "kafka_acl" "pubsub_es_topic_indexer_group_access" {
+ acl_host                     = "*"
+ acl_operation                = "Read"
+ acl_permission_type          = "Allow"
+ acl_principal                = "User:CN=dev-enablement/es-topic-indexer"
+ id                           = (known after apply)
+ resource_name                = "es-topic-indexer"
+ resource_pattern_type_filter = "Literal"
+ resource_type                = …
```

[DENA-427] allow access to pubsub-examples topic for es-topic-indexer

---

dev-aws/kafka-shared/pubsub-examples.tf

The quotas will all be recreated.
The plan is:
```
id                           = "User:CN=dev-enablement/example-consume-process-batch|*|Read|Allow|Group|example-consume-process-batch|Literal"
}
id                           = "User:CN=dev-enablement/example-consume-process-batch|*|Read|Allow|Topic|dev-enablement.pubsub-examples|Literal"
}
}
~ id          = …
```

kafka-shared: refactor pubsub examples to use the new tls-app module

---

dev-aws/kafka-shared/otel.tf

Plan:
```
resource "kafka_acl" "producer_acl" {
id                           = "User:CN=otel/collector|*|Write|Allow|Topic|otel.otlp_spans|Literal"
}
+ "consumer_byte_rate" = 5242880
}
~ id          = "User:CN=otel/collector|user" -> (known after apply)
}
id                           = "User:CN=otel/tempo-distributor|*|Read|Allow|Group|processor-tempo|Literal"
}
id                           = "User:CN=otel/tempo-distributor|*|Read|Allow|Topic|otel.otlp_spans|Literal"
}
}
~ id          = …
```

DENA-437: kafka-shared: dev: refactored otel to use the tls-app module

---

dev-aws/kafka-shared/iam.tf
prod-aws/kafka-shared/iam.tf

Think my editor ran `terraform fmt` on these files.

Add customer-auth-provider to prod

---

prod-aws/finance/credit-risk.tf

Related PR:
- https://github.com/utilitywarehouse/kafka-cluster-config/pull/178

feat(FIN-1054): add topic for credit risk model input parameters [PROD]

---

dev-aws/kafka-shared/dev-enablement/pubsub-test-throughput.tf

- Using another principal without quota for throughput test

PLA2-89: franz throughput test

---

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf

Add kafka consumer config for two data infra kafka consumers

EHD-419/di-kafka-source-config

---

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf

- Adds deadletter topic with 2 month retention.
- Correct topic names from map format to list (removes the `( )`)

Adds deadletter for Fabricator

---

dev-aws/kafka-shared-msk/data-infra/data-infra.tf

This reverts commit 4ec40608a1f9a5a9223fa5dfb3d5853eee9bce73.

Revert "Keep source compression to debug mm2 (#204)"

---

README.md

To avoid confusion/concern for people reading Terraform output from this repo, e.g. if something breaks and you read that warning, you might think it's related

Document expected deprecation warning

---

dev-aws/finance/credit-insight.tf

Goal is to test out changes to how the reports are produced.

feat(insights): Add experimental topic for insights

---

dev-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf

was seeing various errors like ` Error: Reference to undeclared resource on customer-proposition.tf line 23, in module "uswitch-data-projector": 23: produce_topics = [kafka_topic.uswitch.data.v1] A managed resource "kafka_topic" "uswitch" has not been declared in the root module.`

reference the topic name in the correct way

---

dev-aws/kafka-shared-msk/README.md
prod-aws/kafka-shared-msk/README.md

Keeping this part here, to be closer to the source

doc(PLA2-94): put documentation in place for migration to MSK

---

prod-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf

https://github.com/utilitywarehouse/customer-proposition-uswitch/blob/main/manifests/overlays/prod/merit/mailer/switch-projector.yaml#L25-L25

update uswitch mailer consumer-group prod

---

dev-aws/kafka-shared-msk/payment-platform/open-banking.tf

- **Define ACLs for open banking topics**
- **Create ACLs for open banking**

payment platform modules

---

.github/workflows/pr.yaml
.pre-commit-config.yaml
.tflint.hcl
dev-aws/customer-billing/topics.tf
dev-aws/finance/account-balance.tf
dev-aws/finance/account-discounts.tf
dev-aws/finance/complaints-fabricator.tf
dev-aws/finance/credit-insight.tf
dev-aws/finance/credit-risk.tf
dev-aws/finance/debt.tf
dev-aws/finance/disputes-fabricator.tf
dev-aws/finance/vulnerabilities-fabricator.tf
dev-aws/kafka-shared-msk/cbc/cbc.tf
dev-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf
modules/tls-app/variables.tf
prod-aws/customer-billing/topics.tf
prod-aws/finance/account-balance.tf
prod-aws/finance/account-discounts.tf
prod-aws/finance/complaints-fabricator.tf
prod-aws/finance/credit-insight.tf
prod-aws/finance/credit-risk.tf
prod-aws/finance/debt.tf
prod-aws/finance/disputes-fabricator.tf
prod-aws/finance/vulnerabilities-fabricator.tf
prod-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf

Adding [tflint](https://github.com/terraform-linters/tflint) to our config.
Want to get this quickly in so that is will help asap in PRs.
Got it to validate on the current main branch by ignoring the current issues.

adding tflint

---

.tflint.hcl
dev-aws/customer-billing/provider.tf
dev-aws/finance/provider.tf
dev-aws/kafka-shared-msk/__env.tf
dev-aws/kafka-shared/__env.tf
exp-1-merit/kafka-shared/provider.tf
exp-1-merit/pubsub-msk/provider.tf
modules/tls-app/provider.tf
prod-aws/customer-billing/provider.tf
prod-aws/finance/provider.tf
prod-aws/kafka-shared-msk/__env.tf
prod-aws/kafka-shared/__env.tf

Added the version constraint to the required providers & enabled the rule in tflint
The rule is described here: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_required_providers.md#terraform_required_providers

DENA-522: Fixed tflint terraform_required_providers & enabled the rule

---

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf

Adds Aggregator which consumes from the customer change topic and produces to the budget plan topic.

Adds budget plan aggregator

---

dev-aws/kafka-shared-msk/iam/iam.tf

related to utilitywarehouse/iam#1732

add castle-processor tls app

---

dev-aws/otel/otel.tf
modules/tls-app/variables.tf
prod-aws/otel/otel.tf

This will allow increased throughput on consuming

PLA2-100: otel: increase consuming quota for tempo distributor

---

dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf
prod-aws/kafka-shared-msk/pubsub/pubsub-examples.tf

We don't really need 10. Keeping 3 to have at least 3 members

PLA2-114: pubsub examples: reduce the number of partitions

---

prod-aws/kafka-shared-msk/pubsub/proximo-examples.tf

PLA2-114: proximo examples: prepare running in prod

---

prod-aws/finance/bq.tf
prod-aws/finance/debt.tf

chore(FIN-899): Create debt payment pages related topics [PROD]

---

dev-aws/kafka-shared-msk/iam/audit.tf

RBAC for deployment https://github.com/utilitywarehouse/go-mono/pull/55

Grant iam-audit cerbos access

---

CODEOWNERS
dev-merit/billing/backend.tf
dev-merit/billing/invoice.tf
dev-merit/billing/provider.tf

Also update CODEOWNERS for billing kafka.

Add Terraform module for Billing Dev

---

prod-aws/billing/backend.tf
prod-aws/billing/invoice.tf
prod-aws/billing/provider.tf

feat(FIN-837): Add Terraform module for Billing Prod

---

dev-merit/billing/billing-pipeline.tf
prod-aws/billing/billing-pipeline.tf

Create billing pipeline related topics.
Related PRs:
- #369

feat(FIN-841): Create billing pipeline topics

---

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf

Fix underscore/hyphen confusion in topic resource names

BTGWS-1340: Resolve MSK workplace-infrastructure Deployment Errors

---

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf

BTGWS-1340: Resolve More `workplace-infrastructure` Deployment Errors

---

CODEOWNERS

We consider these teams gathered enough experience on MSK to manage their PRs on their own

Transfer code ownership to CBC and IAM

---

CODEOWNERS

Update CODEOWNERS (account-platform -> account-identity)

---

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf

topic names wrong; not sure how I managed that :(

BTGWS-1340: Fix workplace-infrastructure corp-netapp-audit topic names

---

dev-aws/kafka-shared-msk/contact-channels/contact-channels.tf

The service will consume without a consumer group. It is intentional

add agent state service to dev

---

dev-aws/kafka-shared-msk/payment-platform/data-staged.tf
prod-aws/kafka-shared-msk/payment-platform/data-staged.tf

Adding the first topic we want to migrate to MSK to test the process.

FPAY-1389: Added payment-data staged topic

---

dev-aws/kafka-shared-msk/payment-platform/notifications-raw.tf
prod-aws/kafka-shared-msk/payment-platform/data-staged.tf
prod-aws/kafka-shared-msk/payment-platform/notifications-raw.tf

Migrating two services along with topics used by them internally.

FPAY-1389: Migrate payment gateway notifs raw to msk

---

dev-aws/finance/account-balance.tf

Now that the topic is stable I think we can compact the log less frequently to reduce the overhead.

Relax compaction settings and add some comments

---

prod-aws/account-platform/topics.tf

[Slack context](https://utilitywarehouse.slack.com/archives/C37EHB3R6/p1723107575905479)

account-platform: Add import block for existing topic

---

prod-aws/customer-billing/topics.tf

Increase the retention for core bill events to allow testing of invoice-producer v2

[BEX] Update topics.tf

---

dev-aws/kafka-shared-msk/billing/data-staged-events.tf

Based on the [instructions](https://wiki.uw.systems/posts/kafka-m-tls-deployment-and-runtime-vz6866gl#terraform-kafka-resources).

FIN-1210: Define TLS modules for billing.DataStagedEventsFinance topic in DEV

---

dev-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
dev-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf
prod-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
prod-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf

Creating notifications-tx, and payment-enriched-txs topics
Creating payment_tx_log_writer module, consuming from both

FPAY-1484: Tx-log-writer MSK

---

dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf
prod-aws/kafka-shared-msk/pubsub/pubsub-examples.tf

Prepare pubsub example for the SimpleConcurrentConsumer that is introduced by https://github.com/utilitywarehouse/uwos-go/pull/1626

DENA-674: pubsub examples: add app for example for consume concurrently

---

prod-aws/kafka-shared-msk/billing/data-staged-events.tf

Includes producer and consumer.
Related PRs:
- https://github.com/utilitywarehouse/kafka-cluster-config/pull/476 
- https://github.com/utilitywarehouse/kafka-cluster-config/pull/482

chore(FIN-1154): Update TLS certificates for 'historical-data-staged-events-finance' topic [PROD]

---

dev-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
dev-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf
prod-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
prod-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf

adding permissions for payment-transaction-query-service and adding prefix to topics with omited team names.

add permissions for service

---

dev-aws/kafka-shared-msk/payment-platform/card-payment.tf
dev-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
dev-aws/kafka-shared-msk/payment-platform/payment-analysis.tf
dev-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf
dev-aws/kafka-shared-msk/payment-platform/reconciliation.tf
prod-aws/kafka-shared-msk/payment-platform/notifications-tx.tf
prod-aws/kafka-shared-msk/payment-platform/payment-enriched-txs.tf

bumping partition values to match what is seen in kafka-ui

use correct partition values

---

dev-aws/kafka-shared-msk/pubsub/pubsub-test-throughput.tf

Doing a throughput test for this

DENA-674: pubsub: prepare resources to test the throughput of the SimpleConsumer vs SimpleConcurrentConsumer

---

dev-aws/kafka-shared-msk/payment-platform/payment-api.tf
dev-aws/kafka-shared-msk/payment-platform/payment.tf
prod-aws/kafka-shared-msk/payment-platform/payment-api.tf
prod-aws/kafka-shared-msk/payment-platform/payment.tf

Adding msk tls module for payment-method.v1.events for payment-api and es indexer

---

dev-aws/kafka-shared-msk/pubsub/pubsub-test-throughput.tf

fix consumer principal

---

dev-aws/kafka-shared-msk/customer-billing/modules.tf
dev-aws/kafka-shared-msk/customer-billing/topics.tf
prod-aws/kafka-shared-msk/customer-billing/modules.tf
prod-aws/kafka-shared-msk/customer-billing/topics.tf

These topics are needed to facilitate our new bill regeneration architecture.

[BEX-1053] - Create new bill regeneration topics on

---

dev-aws/kafka-shared-msk/billing/transaction-auditor-events.tf
prod-aws/kafka-shared-msk/billing/transaction-auditor-events.tf

It also includes configuration for producer and consumers.

feat(FIN-1204): Add transaction-auditor-diffs topic to billing namespace

---

prod-aws/kafka-shared-msk/README.md

Adding the instructions on how to use the files added here: https://github.com/utilitywarehouse/kubernetes-manifests/pull/97481

DENA-969: Added instructions on how to create the terraform-applier CRD file

---

.pre-commit-config.yaml
.semgrep/rules.yaml
.tflint-msk.hcl

Update plugin to enforce the newly introduced rule https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/blob/main/rules/msk_topic_name.md

DENA-974: Enforce topic names prefixes

---

modules/tls-app/README.md

Following on from 859c8b716d44e65733498b8cd67ba63f9304e9e8
Ticket: DENA-994

Update docs for defining quotas on `tls-app`

---

.pre-commit-config.yaml
.tflint-msk.hcl

Using new release https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.2.0
Enable also fixing when running precommit.

DENA-671: tflint plugin 1.2.0: replication factor validation

---

prod-aws/kafka-shared-msk/README.md

- Fix some some typos
- Document our `tflint` plugin

Document our `tflint` plugin

---

.semgrep/rules.yaml

Prohibit ignoring `tflint` rule on MSK topics

---

.tflint-msk.hcl

Updating to latest https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.3.0

DENA-671: tflint plugin 1.3.0: compression type validation

---

.tflint-msk.hcl

The release is here: https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.4.0

DENA-671: Using new version of plugin with new checks.

---

.tflint-msk.hcl

Roll out new release that includes tiered storage validation
https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.5.0

DENA-671: Release new plugin version: tiered storage validation

---

dev-aws/kafka-shared-msk/account-identity/verification.tf

some [slack context](https://utilitywarehouse.slack.com/archives/C04UATB9796/p1729778811438459?thread_ts=1729764953.586049&cid=C04UATB9796)

update common name for verification indexer

---

dev-aws/kafka-shared-msk/account-identity/account.tf
dev-aws/kafka-shared-msk/account-identity/legacy_account.tf

These were fixed automatically by running the tflint plugin from this PR: https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/pull/24

DENA-671: Enable tiered storage for topics with 3 days retention

---

.tflint-msk.hcl

See https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.5.1

DENA-671: New plugin version - tiered storage for 3 days inclusive

---

.tflint-msk.hcl

See release https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.6.0 for details

DENA-671:  new plugin version

---

prod-aws/kafka-shared-msk/account-identity/verification.tf

follow up to https://github.com/utilitywarehouse/kafka-cluster-config/pull/650

prod: update common name for verification indexer

---

.tflint-msk.hcl

Updating to https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/pull/27 that includes compacted topics validation

DENA-671: Update to latest plugin version

---

README.md
prod-aws/kafka-shared-msk/README.md

DENA-671: Update readmes

---

.pre-commit-config.yaml

I felt these needed a bit of improvement. 
Using format=default should help people in debugging the issues they get

DENA-671: Updated format for the MSK tflint run & comment on it

---

CONTRIBUTING.md

Got notified on this thread about this: https://utilitywarehouse.slack.com/archives/C0536L8V7EU/p1730909839870669?thread_ts=1730907320.532009&cid=C0536L8V7EU

DENA-671: Update the pre-commit instructions

---

dev-aws/kafka-shared-msk/account-identity/verification.tf
dev-aws/kafka-shared-msk/iam/iam.tf
prod-aws/kafka-shared-msk/account-identity/verification.tf
prod-aws/kafka-shared-msk/iam/iam.tf

On autopilot before and had it consuming from the wrong topic

ACC-770 msk/account-identity: fix verification di kafka source config

---

dev-aws/kafka-shared-msk/account-identity/account.tf
prod-aws/kafka-shared-msk/account-identity/account.tf

Reverts utilitywarehouse/kafka-cluster-config#697

Revert "[A&I] update typo"

---

prod-aws/kafka-shared-msk/customer-billing/modules.tf
prod-aws/kafka-shared-msk/customer-billing/topics.tf

context - https://github.com/utilitywarehouse/kubernetes-manifests/pull/99563
dev changes - https://github.com/utilitywarehouse/kafka-cluster-config/pull/700

add bex fulfilment large invoice topics to prod

---

dev-aws/kafka-shared-msk/pubsub/pubsub-test-throughput.tf

Add topic for throughput test to write to

---

dev-aws/kafka-shared-msk/account-identity/analytics.tf
dev-aws/kafka-shared-msk/account-identity/data_infra.tf

https://github.com/utilitywarehouse/kubernetes-manifests/pull/101338

Add topic for move out notification

---

CODEOWNERS
dev-aws/kafka-shared-msk/energy-platform/energy-platform.tf

The intention is to delete the old topic and create a new one with the correct name.

rename meter read events

---

prod-aws/kafka-shared-msk/customer-billing/modules.tf
prod-aws/kafka-shared-msk/customer-billing/topics.tf

Allows email sender module to consume from invoice-fulfillment topic for when we implement the new scheduling.

[BEX-1009] - Add email-sender module and DLQ.

---

dev-aws/otel/otel.tf

This collector only needs to read from the sampled spans
Ticket: DENA-1238

Add app for OTEL GoC collector

---

prod-aws/otel/otel.tf

This collector reads off the sampled topic and writes to Grafana Cloud's tempo
Ticket: DENA-1269

Add app for Grafana Cloud forwarding collector

---

dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf

I want to test backing up this topic

Let kafka-connect consume from pubsub-examples

---

dev-aws/kafka-shared-msk/energy-platform/energy-platform.tf

[dev-aws] add missing meter read indexer cert for MSK

---

dev-aws/kafka-shared-msk/dev-enablement/kafka-connect.tf

I want to see how much it would cost backing up the whole dev cluster

test: backup the whole dev cluster

---

dev-aws/kafka-shared-msk/dev-enablement/kafka-connect.tf
dev-aws/kafka-shared-msk/dev-enablement/msk-test-backup-restore.tf

The customer-proposition.service-status.events.v3 topic has 18.4 GiB after backup with 71 013 841 records in it.

DENA 1329 restore big topic

---

prod-aws/kafka-shared-msk/iam/iam.tf

following https://github.com/utilitywarehouse/kubernetes-manifests/pull/107459

[A&I] add prod consumer for login-service

---

dev-aws/kafka-shared-msk/dev-enablement/kafka-connect-msk-backup.tf

Setting up a new kafka connect cluster to test parallel restoring on multiple nodes

Prepare separate cluster for kafka connect

---

prod-aws/kafka-shared-msk/customer-support/vulnerability.tf

Adds Kafka client certificate config for access to produce to the Vulnerability topic. This is for the Origin customer importer.

[prod/customer-support] Add Origin customer importer

---

dev-aws/kafka-shared-msk/account-identity/legacy_account.tf

needed for https://github.com/utilitywarehouse/kubernetes-manifests/pull/108198

[A&I] to msk relay

---

dev-aws/kafka-shared-msk/billing/data-staged-events.tf

Don't need infinite retention in dev for this

Update dev retention for billing.DataStagedEventsFinance

---

dev-aws/kafka-shared-msk/ledgers/ledger.tf
prod-aws/kafka-shared-msk/ledgers/ledger.tf

Not sure if it allow to define a regex pattern

LAB-57: Added ACL for ledger-operational group

---

dev-aws/kafka-shared-msk/unicom/topics.tf

Increase max message byte to be 512MB

increase max message byte to 512 MB

---

dev-aws/kafka-shared-msk/energy-platform/gentrack.tf

Adds sink topic for registration events produced by the gentrack-webhook-listener

[EIN-1844] Registration events sink topic

---

dev-aws/kafka-shared-msk/energy-platform/gentrack.tf

Adds the consumer group for gentrack migration consumers

adds consumer groups for gentrack migration consumers

---

dev-aws/kafka-shared-msk/energy-platform/meterpoints.tf

This PR updates meterpoint module to align with existing meterpoint consumer. That module hasn't been used yet so it is safe to rename it

meterpoint module updated

---

dev-aws/kafka-shared-msk/customer-support/vulnerability.tf

Adds batch job for assessment removals.
Ref CS-2113

[dev/cs] Vulnerability - Add assessment removal tool

---

prod-aws/kafka-shared-msk/account-identity/legacy_account.tf

Reverts utilitywarehouse/kafka-cluster-config#921

Revert "Add tls module for braze backfill relay [prod]"

---

dev-aws/kafka-shared-msk/account-identity/legacy_account.tf

Reverts utilitywarehouse/kafka-cluster-config#920

Revert "Add tls module for braze backfill relay"

---

dev-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf
prod-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf

Adds MSK topics for the shared cluster with infinite retention for `service_status_v4`.

feat(CPQ-69): msk topics for service status v4

---

prod-aws/kafka-shared-msk/billing/billing.tf

This should hopefully stop the errors we are seeing:
https://uw.grafana.net/goto/fT5hra_Hg?orgId=1

Increase number of partitions

---

.semgrep/rules.yaml
CODEOWNERS

- **Update CODEOWNERS**
- **More rules to semgrep to not allow some tflint ignores.**

Code owners & updated semgrep rules

---

dev-aws/kafka-shared-msk/customer-support/coffee.tf

[dev] Use 1 month for coffee services

---

CODEOWNERS

This will prevent adding system to all PRs

Generated files are not owned by anybody
