utilitywarehouse/kafka-cluster-config

dev-merit/kafka-shared/otel.tf
For consuming we also need access to the group.
Renamed the resources to have more meaningful names
=> otel spans: add group access for tempo-distributor

dev-merit/kafka-shared/pubsub-examples.tf
The examples are here: https://github.com/utilitywarehouse/dev-enablement-mono/tree/main/services/pubsub-examples
=> PLA2-7: pubsub examples: added topic, acls and quotas for running the pubsub examples created in dev-enablement-mono

prod-aws/kafka-shared/customer-billing.tf
Create the `bex.internal.bill_fulfilled` topic in production that will contain a `InvoiceFulfilledEvent` (link)[https://github.com/utilitywarehouse/bex-protos/blob/main/fulfilment/internal-events.proto#L33] in an envelope.
Add a producer&consumer for that topic
=> [BEX-346] add bex.internal.bill_fulfilled topic and producer and consumer in prod

dev-aws/kafka-shared/customer-billing.tf, prod-aws/kafka-shared/customer-billing.tf
This is an attempt to rename the consumer group. The `bex.` prefix in the consumer group can be used for permissions based on regexes (see https://utilitywarehouse.slack.com/archives/C0536L8V7EU/p1700065295553729?thread_ts=1700058548.486999&cid=C0536L8V7EU)
=> [BEX] change consumer group name

dev-aws/customer-billing/topics.tf
The topics didn't appear and I wasn't sure how I could check that the files are okay. Running `terraform validate` locally returned this:
```
│ Error: Invalid resource name
│
│   on topics.tf line 407, in resource "kafka_topic" "account-payment-details.v1":
│  407: resource "kafka_topic" "account-payment-details.v1" {
│
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
```
This PR fixes the problem
=> [BEX-481] fix resource name

prod-aws/customer-billing/backend.tf, prod-aws/customer-billing/provider.tf, prod-aws/customer-billing/topics.tf
Create the topics that we currently have on the old kafka cluster in the new kafka cluster based on this list: https://github.com/utilitywarehouse/kubernetes-manifests/blob/master/prod-aws/customer-billing/kafka-topic-applier/topics.yaml
Configuration is changed because the configured values are too high, we applied the same changes we did in dev
=> [BEX-482] add production setup for kafka topics for customer-billing

dev-aws/kafka-shared/iam_cerbos-audit.tf, dev-aws/kafka-shared/iam_identitydb.tf, prod-aws/kafka-shared/iam_cerbos-audit.tf
Use provided modules to cleanup defining producers and consumers. Naming has tweaked intentionally; once clients have migrated will raise a PR to remvoe the old definitions.
=> Migrate IAM cerbos audit to kafka module(s)

dev-aws/kafka-shared/iam_cerbos-audit.tf, dev-aws/kafka-shared/iam_identitydb.tf, modules/tls-app/main.tf, modules/tls-app/provider.tf, modules/tls-app/variables.tf
- introduce new module for an app that defines both consumers & producers and a single quota.
- fixes the quota for iam-policy-decision-api which was defined twice before: once by the consumer module & once by the producer
This comes from the need of having a single quota / user (in our case per certificate) and I think it would be also simpler for devs to define like this.
If this is fine, I'll migrate all the consumers/producers to the new module, and remove the consumer & producer modules afterwards. 
The plan in de-aws is:
```
+ create
- destroy
- resource "kafka_acl" "producer_acl" {
- acl_host …
```
=> DENA-437: new module for app definition includes both consumers & producers

dev-aws/kafka-shared/iam_identitydb.tf, modules/tls-app/main.tf, prod-aws/kafka-shared/iam_identitydb.tf
Renaming from producer_quota to just quota, as it contains also consuming rate and it is one per app.
The move blocks will make sure the resource is not destroyed, but it is kept upon applying.
The plan for dev is:
```
resource "kafka_quota" "quota" {
id          = "User:CN=auth/iam-policy-decision-api|user"
}
╷
│ Warning: Argument is deprecated
│
│   with provider["registry.terraform.io/mongey/kafka"],
│   on provider.tf line 9, in provider "kafka":
│    9: provider "kafka" {
│
│ This parameter is now deprecated and will be removed in a later release, please use `ca_cert` instead.
│
│ (and 5 more similar warnings elsewhere)
```
=> kafka-shared: renamed the quota in the tls-app

dev-aws/kafka-shared/customer-billing.tf
Some of the moved items need to be replaced, so this means destroy + add, so there will be a little bit of disruption.
The plan is:
```
- destroy
id                           = "User:CN=customer-billing/bills-total-api|*|Read|Allow|Group|bex.bills-total-api-reader|Literal"
}
id                           = "User:CN=customer-billing/bills-total-api|*|Read|Allow|Topic|bex.internal.bill_fulfilled|Literal"
}
+ …
```
=> DENA-437: kafka-shared: dev: refactor customer billing to use the new tls-app module

prod-aws/kafka-shared/customer-billing.tf
Plan:
```
- destroy
id                           = "User:CN=customer-billing/bills-total-api|*|Read|Allow|Group|bex.bills-total-api-reader|Literal"
}
id                           = "User:CN=customer-billing/bills-total-api|*|Read|Allow|Topic|bex.internal.bill_fulfilled|Literal"
}
}
~ id          = "User:CN=customer-billing/bills-total-api|user" -> (known after apply)
}
resource "kafka_acl" …
```
=> DENA-437: kafka-shared: prod: refactor customer billing to use the new tls-app module

dev-aws/kafka-shared/iam_cerbos-audit.tf, dev-aws/kafka-shared/iam_credentials.tf, dev-aws/kafka-shared/iam_identitydb.tf
Quotas need to be replaced, so there will be some disruption.
The plan is:
```
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Group|exporter-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Topic|auth.iam-cerbos-audit-v1|Literal"
}
}
~ id          = …
```
=> DENA-437: kafka-shared: dev: refactor iam to use the tls-app module

prod-aws/kafka-shared/iam_cerbos-audit.tf, prod-aws/kafka-shared/iam_credentials.tf, prod-aws/kafka-shared/iam_identitydb.tf
Plan is:
```
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Group|exporter-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Topic|auth.iam-cerbos-audit-v1|Literal"
}
}
~ id          = "User:CN=auth/iam-cerbos-audit-exporter|user" -> (known after apply)
}
id …
```
=> DENA-437: kafka-shared: prod: refactor iam to use the tls-app module

prod-aws/kafka-shared/otel.tf
Plan:
```
resource "kafka_acl" "producer_acl" {
id                           = "User:CN=otel/collector|*|Write|Allow|Topic|otel.otlp_spans|Literal"
}
+ "consumer_byte_rate" = 5242880
}
~ id          = "User:CN=otel/collector|user" -> (known after apply)
}
id                           = "User:CN=otel/tempo-distributor|*|Read|Allow|Group|processor-tempo|Literal"
}
id                           = …
```
=> DENA-437: kafka-shared: prod: refactored otel to use the tls-app module

.github/workflows/pr.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, dev-aws/finance/debt.tf, dev-aws/finance/direct-debits.tf, dev-aws/finance/disputes-fabricator.tf, dev-aws/kafka-shared/customer-billing.tf, dev-aws/kafka-shared/iam.tf, dev-aws/kafka-shared/kafka-ui.tf, dev-aws/kafka-shared/mirror-maker.tf, dev-aws/kafka-shared/otel.tf, dev-aws/kafka-shared/pubsub-examples.tf, exp-1-merit/kafka-shared/kafka-ui.tf, exp-1-merit/kafka-shared/pdp-audit.tf, exp-1-merit/kafka-shared/pubsub-examples.tf, exp-1-merit/pubsub-msk/kafka-ui.tf, exp-1-merit/pubsub-msk/pubsub-examples.tf, exp-1-merit/pubsub-msk/tf-applier.tf, modules/tls-app/main.tf, modules/tls-app/variables.tf, prod-aws/finance/complaints-fabricator.tf, prod-aws/finance/debt.tf, prod-aws/finance/disputes-fabricator.tf, prod-aws/kafka-shared/customer-billing.tf, prod-aws/kafka-shared/iam.tf, prod-aws/kafka-shared/kafka-ui.tf, prod-aws/kafka-shared/mirror-maker.tf, prod-aws/kafka-shared/otel.tf
Run the hook to format all the code and enforce this via CI to avoid
regressions. This is to keep formatting consistent and not a thing to
worry/think about when developing or in PRs.
This does rely on the local version of `terraform` people are running. I
think this can cause issues when running `terraform apply` across
different versions, but it should be fine for `terraform fmt` which I
can't imagine changes output much between versions.
=> Add `pre-commit` config to run `terraform fmt`

dev-aws/kafka-shared/pubsub-examples.tf
Looks like the contents of this PR were accidentally deleted during moving to modules: 
https://github.com/utilitywarehouse/kafka-cluster-config/pull/114
I assume, now changes to dev-merit should be added to dev-aws.
`make-plan` output:
```
+ resource "kafka_acl" "group_acl" {
+ acl_host                     = "*"
+ acl_operation                = "Read"
+ acl_permission_type          = "Allow"
+ acl_principal                = "User:CN=dev-enablement/es-topic-indexer"
+ id                           = (known after apply)
+ resource_name                = "es-topic-indexer"
+ resource_pattern_type_filter = "Literal"
+ resource_type                = "Group"
}
+ resource "kafka_acl" "topic_acl" {
+ acl_host                     = "*"
+ acl_operation …
```
=> [DENA-427] recreate es-topic-indexer policy for pubsub-exapmles

dev-aws/kafka-shared/__env.tf, dev-aws/kafka-shared/backend.tf, prod-aws/kafka-shared/__env.tf, prod-aws/kafka-shared/backend.tf
Using the same name "__env.tf" as in the terraform repo https://github.com/utilitywarehouse/terraform
=> PLA2-70: kafka-shared: moved tf module settings to a single file

dev-aws/kafka-shared/dev-enablement/pubsub-examples.tf
To be in line with the guidelines https://github.com/utilitywarehouse/kafka-cluster-config/tree/dev-enablement-fix-consumer-groups/dev-aws/kafka-shared#contributing.
=> PLA2-76: pubsub examples: add team prefix to the consumer groups

prod-aws/finance/account-balance.tf
At first, I thought 20 days would work but I was not thinking about the current use case where we copy messages from the old topic and expect them to be compacted when a new version is published.
=> Set compaction lag to two hours

dev-aws/kafka-shared-msk/energy-budget-plan/Makefile, dev-aws/kafka-shared-msk/energy-budget-plan/__env.tf, dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf
- Creates 3 topics for energy-budget-plan: `energy-budget-plan.eqdb-loader`, `energy-budget-plan.budget-plan` and `energy-budget-plan.customer-change`
- Configures an EQDB loader process as producer on `energy-budget-plan.eqdb-loader`
- Configures a Budget Plan Fabricator process as the consumer of `energy-budget-plan.eqdb-loader` and producer on `energy-budget-plan.customer-change`
- Configures Budge Plan Calculator as consumer and producer of `energy-budget-plan.budget-plan`
- Cert config in wip PR https://github.com/utilitywarehouse/kubernetes-manifests/pull/85143
=> Add basic topic config for energy-budget-plan namespace

dev-aws/kafka-shared/dev-enablement/pubsub-examples.tf, modules/tls-app-v2/README.md, modules/tls-app-v2/main.tf, modules/tls-app-v2/provider.tf, modules/tls-app-v2/variables.tf
See the linked ticket for details: https://linear.app/utilitywarehouse/issue/PLA2-83/tls-app-module-allow-consumer-group-for-multiple-topics
The plan is to migrate all modules one by one and after that, remove the old tls-app module and rename the tls-app-v2 to just tls-app.
=> PLA2-83: tls-app module: allow same consumer group for multiple topics

dev-aws/kafka-shared/otel/otel.tf
Plan is clean:
```
kafka_topic.otlp_spans: Refreshing state... [id=otel.otlp_spans]
module.tempo_distributor.kafka_quota.quota: Refreshing state... [id=User:CN=otel/tempo-distributor|user]
module.tempo_distributor.kafka_acl.group_acl["processor-tempo"]: Refreshing state... [id=User:CN=otel/tempo-distributor|*|Read|Allow|Group|processor-tempo|Literal]
module.otel_collector.kafka_quota.quota: Refreshing state... [id=User:CN=otel/collector|user]
module.otel_collector.kafka_acl.producer_acl["otel.otlp_spans"]: Refreshing state... [id=User:CN=otel/collector|*|Write|Allow|Topic|otel.otlp_spans|Literal]
module.tempo_distributor.kafka_acl.topic_acl["otel.otlp_spans"]: Refreshing state... [id=User:CN=otel/tempo-distributor|*|Read|Allow|Topic|otel.otlp_spans|Literal]
Terraform will perform the …
```
=> PLA2-83: tls-app fix: migrate otel dev

dev-aws/kafka-shared/iam/iam.tf
Resources are not affected. Plan is:
```
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Group|exporter-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth/iam-cerbos-audit-indexer|*|Read|Allow|Group|indexer-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth-customer/iam-credentials-v1-indexer|*|Read|Allow|Group|indexer-iam-credentials-v1|Literal"
}
id                           = "User:CN=auth-customer/di-kafka-source-customer-login-failed|*|Read|Allow|Group|iam.di-kafka-source-customer-login-failed|Literal"
}
resource …
```
=> PLA2-83: tls-app fix: migrate dev iam

dev-aws/kafka-shared/customer-billing/customer-billing.tf, prod-aws/kafka-shared/customer-billing/customer-billing.tf
Plan is for both dev and prod:
```
id                           = "User:CN=customer-billing/billing-fulfilment-public-events-translator|*|Read|Allow|Group|bex.billing-fulfilment-public-events-translator|Literal"
}
id                           = "User:CN=customer-billing/bills-total-api|*|Read|Allow|Group|bex.bills-total-api-reader|Literal"
}
```
=> PLA2-83: tls-app fix: migrate dev and prod customer-billing

prod-aws/kafka-shared/otel/otel.tf
Plan is:
```
id                           = "User:CN=otel/tempo-distributor|*|Read|Allow|Group|processor-tempo|Literal"
}
```
=> PLA2-83: tls-app fix: migrate prod otel

prod-aws/kafka-shared/iam/iam.tf
Plan is clean:
```
id                           = "User:CN=auth/iam-cerbos-audit-exporter|*|Read|Allow|Group|exporter-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth/iam-cerbos-audit-indexer|*|Read|Allow|Group|indexer-iam-cerbos-audit-v1|Literal"
}
id                           = "User:CN=auth-customer/iam-credentials-v1-indexer|*|Read|Allow|Group|indexer-iam-credentials-v1|Literal"
}
id                           = "User:CN=auth-customer/di-kafka-source-customer-login-failed|*|Read|Allow|Group|iam.di-kafka-source-customer-login-failed|Literal"
} …
```
=> PLA2-83: tls-app fix: migrate prod iam

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf
The plan is clean:
```
id                           = "User:CN=energy-budget-plan/calculator|*|Read|Allow|Group|energy-budget-plan.calculator-v1|Literal"
}
id                           = "User:CN=energy-budget-plan/eqdb-fabricator|*|Read|Allow|Group|energy-budget-plan.eqdb-fabricator-customer-change-v1|Literal"
}
id                           = "User:CN=energy-budget-plan/eqdb-fabricator|*|Read|Allow|Group|energy-budget-plan.eqdb-fabricator-loader-v1|Literal"
}
```
=> PLA2-83: tls-app fix: migrate dev msk energy-budget-plan

dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf
Plan is clean:
```
id                           = "User:CN=pubsub/example-consume-process-batch|*|Read|Allow|Group|pubsub.example-consume-process-batch|Literal"
}
id                           = "User:CN=pubsub/example-consume-process-individually|*|Read|Allow|Group|pubsub.example-consume-process-individually|Literal"
}
```
=> PLA2-83: tls-app fix: migrate dev msk pubsub

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf, dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf, dev-aws/kafka-shared/customer-billing/customer-billing.tf, dev-aws/kafka-shared/dev-enablement/pubsub-examples.tf, dev-aws/kafka-shared/iam/iam.tf, dev-aws/kafka-shared/otel/otel.tf, prod-aws/kafka-shared/customer-billing/customer-billing.tf, prod-aws/kafka-shared/iam/iam.tf, prod-aws/kafka-shared/otel/otel.tf
The "moved" blocks are no longer necessary, as all modules were applied.
No resource will be affected.
Tested on dev-aws `iam` and got on plan:
```
No changes. Your infrastructure matches the configuration.
```
=> PLA2-83: tls-app fix: remove the "moved" blocks

dev-aws/kafka-shared-msk/pubsub/mm2-big-remote-load-test.tf, dev-aws/kafka-shared/pubsub/mm2-big-remote-load-test.tf
We need to limit the throughput to give MSK a chance to write quickly in the remote storage
=> PLA2-86: prepare mirror maker with reduced quota.

modules/tls-app/main.tf
Quota was not enforced, as the entity name shouldn't contain the "User:" prefix.
Tested without the prefix and now it is ok.
=> PLA2-86: tls-app: fix quota definition

dev-aws/kafka-shared/iam/iam.tf
They must have at most 64 chars.
All 4 password reset ones exceeded this limit.
And instead of renaming just those, I'd rather rename all di-kafka-sources.
=> Rename cert names

prod-aws/customer-billing/topics.tf
We have changed the configuration in topics to have more reasonable sizes. The `replicated-billing-engine-events` topic was configured to 1MB because we didn't expect any messages larger than that. The MM stopped (silently; errors in logs) replicating that topic.
I used the redpanda UI to identify the offending message, the copied message was (when stored as JSON) 7.9MB - this includes some metadata but is mainly the raw payload. 
This PR increases the message size for that topic to 10MB
=> [BEX-482] increase the message size on the topic

prod-aws/customer-billing/topics.tf
MM failed again with:
```
org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
[2024-03-19 13:10:59,203] ERROR [MirrorSourceConnector|task-3] WorkerSourceTask{id=MirrorSourceConnector-3} failed to send record to replicated-billing-engine-events:  (org.apache.kafka.connect.runtime.AbstractWorkerSourceTask:415)
```
Increase message size again by factor 10
=> [BEX-482] kafka prod increase message size

prod-aws/customer-billing/topics.tf
We have to migrate topic by topic because MM failed to run with all topics and consumer groups configured. This removes topics that aren't used by BEX as well as `invoice-diffs` that is not referenced anywhere and dummy topics. I will change the services that use the dummy topic so that the topic can be omitted
=> [BEX] remove non bex topics

dev-aws/customer-billing/topics.tf, prod-aws/customer-billing/topics.tf
`replicated-bill-core-model` and `replicated-internal-bill-core-model` both contain the same event and both had 1 consumer. The consumer on `replicated-bill-core-model` will consume from `replicated-internal-bill-core-model`
=> [BEX] remove replicated-bill-core-model

dev-aws/kafka-shared-msk/contact-channels/contact-channels.tf, prod-aws/kafka-shared-msk/README.md, prod-aws/kafka-shared-msk/contact-channels/contact-channels.tf
Added also mention in the README
=> Rename contact-channels topics to use `-` instead of `_` in the prefix

dev-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf
error message in tf applier ui: `unable to init module: err:exit status 1 Error: Invalid resource name on customer-proposition.tf line 1, in resource "kafka_topic" "uswitch.data.v1": 1: resource "kafka_topic" "uswitch.data.v1" { A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.`
=> fix tf resource name

dev-aws/kafka-shared-msk/pubsub/pubsub-examples.tf
It contains only temporary data, so we didn't need to keep it for that long
=> pubsub-examples msk: decrease the retention policy

dev-aws/kafka-shared/iam/iam.tf
Draft for new topic that will allow CBC to access the password management events produced by auth-customer.iam-credentials-v1
=> create new topic to forward password management events

prod-aws/customer-billing/topics.tf
We had 3 different dummy topics on our old cluster. They were used when services should not read events but the code didn't have the topic as optional. This topic will be used for all those cases. It should never have any events on it
=> [BEX-482] add dummy topic

dev-aws/kafka-shared/dev-enablement/proximo-examples.tf
Add test config configuration, in order to test the proximo instance
=> [PLA2-95] allow test proximo access to shared kafka cluster

dev-aws/customer-billing/topics.tf, prod-aws/customer-billing/topics.tf
This are temporary topics that will only live for the transition towards bex generated bills. That is the reason we are adding them here rather than on the shared kafka.
=> [BEX-793] add topics for the exstream and bex fulfillment

.tflint.hcl, dev-aws/customer-billing/provider.tf, dev-aws/finance/provider.tf, dev-aws/kafka-shared-msk/__env.tf, dev-aws/kafka-shared/__env.tf, exp-1-merit/kafka-shared/provider.tf, exp-1-merit/pubsub-msk/provider.tf, modules/tls-app/provider.tf, prod-aws/customer-billing/provider.tf, prod-aws/finance/provider.tf, prod-aws/kafka-shared-msk/__env.tf, prod-aws/kafka-shared/__env.tf
The rule is described here: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_required_version.md 
Picked 1.5.0 as the minimum version as it's not very old, but not very recent either, it is from [12 June 2023](https://github.com/hashicorp/terraform/releases/tag/v1.5.0) and should work with repo
=> DENA-522: Fixed tflint terraform_required_version & enabled the rule

dev-aws/kafka-shared/customer-billing/customer-billing.tf, prod-aws/kafka-shared/customer-billing/customer-billing.tf
The new fulfilment-router will read the failed events from `invoice_fulfillment_deadletter` and reroute them to exstream.
This changes allow the router to consume from that topic
=> [BEX-801] add new consumer for invoice_fulfillment_deadletter

dev-aws/kafka-shared/customer-billing/customer-billing.tf
Allow the mail sender to consume from the bex.internal.bill_fulfilled topic
=> [BEX-824] allow mail sender to consume bex.internal.invoice_fulfilled

dev-aws/kafka-shared-msk/iam/iam.tf
fixes naming convention for consumer group created for iams castle processor.
=> update consumer group for castle processor

prod-aws/kafka-shared-msk/customer-billing/customer-billing.tf, prod-aws/kafka-shared/customer-billing/customer-billing.tf
Copies the configuration from dev. Creates a consumer for the existing bex.internal.bill_fulfilled topic on the shared kafka and a new producer for bex.internal.mail_sender_deadletter on the shared msk kafka cluster.
Also adds the dashboard producer for manual testing.
=> [BEX-829] create production consumer&producer for mail sender

dev-aws/finance/account-enrichment.tf, dev-aws/finance/account-legacy.tf
This PR is a a breakdown of #750
https://linear.app/utilitywarehouse/issue/FIN-898/migrate-account-events-related-topics
Create two new tf files for the new kafka configs (x3)
legacy.account.events.fwd
account-enrichment.events
account-enrichment.eqdb-loader.customer.events
=> chore(finance):Migrate kafka topics #898 

dev-aws/kafka-shared-msk/customer-billing/consumers.tf, dev-aws/kafka-shared-msk/customer-billing/producers.tf, prod-aws/kafka-shared-msk/customer-billing/consumers.tf, prod-aws/kafka-shared-msk/customer-billing/producers.tf
The terraform applier failed with: 
```
Error: Duplicate module call
on producers.tf line 1:
1: module "mail_sender" {
A module call named "mail_sender" was already defined at
consumers.tf:22,1-21. Module calls must have unique names within a module.
```
Combine the consumer&producer in one module. I will rethink the filenames later
=> [BEX-864] remove duplicated module

dev-aws/finance/direct-debits.tf
This PR is a breakdown of #750
https://linear.app/utilitywarehouse/issue/FIN-899/migrate-topics-related-to-debt-payments-page
Added to the direct-debits.tf two new kafka topics:
- dd_rejections_file_available_events
- dd_rejections_fabrication_failures
=> chore(finance): migrate kafka topics dd rejections #900 [DEV]

prod-aws/otel/otel.tf
Reducing to 1 day retention -> this gives Tempo 1 day for processing the lag.
In worst case scenario, when tempo goes down during the week-end we'll have only the traces 1 day before.
=> otel prod: reduce retention to 1 day

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf
define access for di-kafka-source applications; 
Will migrate from having certificate/di-kafka-source per app to have a single certificate for all this related deployments to share.
Once the deployments are migrated in manifests, will follow up a PR to clean the ones defined per deployment
=> Bp di kafka source config

dev-aws/kafka-shared-msk/energy-budget-plan/energy-budget-plan.tf
existing di kafka source deployments have been migrated to use the new certificate; old configuration can be removed
=> remove ununsed config

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf
Some insistance we use legacy "corp*" namespace for kube
Rule on cert name enforced by kyverno
=> BTGWS-1340: Use legacy `corp-*` kube namespace for cert prefix

prod-aws/customer-billing/topics.tf
Double the topic's retention to facilitate our performance testing.
=> [BEX-938] - Double retention time of transition.bex.fulfilment_request.

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf
Data infra suggested separate consumer groups for each topic
Is it necessary to manually delete the old ACLs/groups?
=> BTGWS-1340: Use different consumer groups for each NetApp audit topic

dev-aws/kafka-shared-msk/pubsub/msk-admin-client.tf, prod-aws/kafka-shared-msk/pubsub/msk-admin-client.tf
This will replace the [tf-kafka-config-admin](https://github.com/utilitywarehouse/kafka-cluster-config/commit/75d10d11dc2ec1e320157e301314e27f308f5e7f) user as it will be used for applying the kafka-config manually too.
=> DENA-750: Add new user msk-admin-client that has admin permissions.

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf
we see the odd message produced which results in MESSAGE_TOO_LARGE
=> BTGWS-1340: Increase workplace-infrastructure netapp-audit `max.message.bytes`

prod-aws/otel/otel.tf
The current 1d period doesn't give us to much space for spikes lately:
https://grafana.prod.aws.uw.systems/d/919b92a8e8041bd567af9edab12c840c/kubernetes-persistent-volumes?var-datasource=default&var-cluster=prod-aws&var-namespace=otel&var-volume=data-kafka-bitnami-2&from=now-2d&to=now
This change means that Tempo has 12h to ingest the data produced, otherwise it will be dropped, which seems fair.
=> otel prod: reduce the retention period to 12h

dev-aws/kafka-shared-msk/billing/data-staged-events.tf
TLS certificates for `historical-bigquery-connector` consumer.
=> FIN-1154: Define TLS modules for historical-data-staged-events-finance topic in DEV

dev-aws/kafka-shared-msk/billing/data-staged-events.tf
`billing/finance-bigquery-connector` service publishes messages to `historical-data-staged-events-finance` topic.
Follow up of #476
=> chore(FIN-1154): Update TLS certificates for 'finance-bigquery-connector' as producer [DEV]

dev-aws/kafka-shared-msk/payment-platform/notifications-raw.tf, prod-aws/kafka-shared-msk/payment-platform/notifications-raw.tf
Both services lack the produce rights. 
The services are already using MSK in dev, luckily prod wasn't affected : )
=> FPAY-1507: Correct access rights for notif listeners

prod-aws/kafka-shared-msk/billing/data-staged-events.tf
After we scaled out the cluster, the producer doubled the throughput and the lag increased significantly to 2.5 Mil records on the big-query-connector.
See this dashboard: https://grafana.prod.aws.uw.systems/d/rrE2HgHVz/msk-kafka-metrics?orgId=1&from=now-6h&to=now&refresh=30s&var-job=msk-shared&var-broker=All&var-topic=billing.DataStagedEventsFinance&var-consumergroup=All
I chose the value of 150KB from the above graph
=> DENA-901: billing: throttle finance_tx_log_staging_connector

dev-aws/kafka-shared-msk/customer-support/vulnerability.tf
cert_common_name needs to be prefixed with the k8s namespace, not the team name.
=> CS-1487 - change to crm

.pre-commit-config.yaml, .tflint-msk.hcl, .tflint-uw-team-hosted.hcl, dev-aws/kafka-shared-msk/pubsub/mirror-maker.tf
We need to split this, as we want to implement rules that apply only for MSK modules
=> DENA-969: Split tflint configs between MSK and team clusters

prod-aws/finance/credit-insight.tf
It also remove unused topics for this initiative.
These topics aren't being used since a refactor was done to insights services: https://github.com/utilitywarehouse/finance-mono/pull/675
Related PR:
- https://github.com/utilitywarehouse/kafka-cluster-config/pull/498
=> feat(FIN-1265): Add topic for credit insight validation errors [PROD]

dev-aws/kafka-shared-msk/__env.tf, dev-aws/kafka-shared-msk/account-identity/__backend.tf, dev-aws/kafka-shared-msk/billing/__backend.tf, dev-aws/kafka-shared-msk/cbc/__backend.tf, dev-aws/kafka-shared-msk/contact-channels/__backend.tf, dev-aws/kafka-shared-msk/customer-billing/__backend.tf, dev-aws/kafka-shared-msk/customer-proposition/__backend.tf, dev-aws/kafka-shared-msk/customer-support/__backend.tf, dev-aws/kafka-shared-msk/data-infra/__backend.tf, dev-aws/kafka-shared-msk/energy-budget-plan/__backend.tf, dev-aws/kafka-shared-msk/iam-audit/__backend.tf, dev-aws/kafka-shared-msk/iam/__backend.tf, dev-aws/kafka-shared-msk/payment-platform/__backend.tf, dev-aws/kafka-shared-msk/pubsub/__backend.tf, dev-aws/kafka-shared-msk/pubsub/mirror-maker.tf
Set the backend definition directly in the modules
Until now, the backend was defined in the terraform applier CRD. These are removed in this PR: https://github.com/utilitywarehouse/kubernetes-manifests/pull/97392
=> DENA-968: Add backend definition to modules

prod-aws/customer-billing/topics.tf
We use this events to be able to validate a big change in our pipeline. The increase from 28 to 35 days means we will have always at least 1 bill run of events on the topic
=> increase retention to allow further testing

prod-aws/kafka-shared-msk/__env.tf, prod-aws/kafka-shared-msk/account-identity/__backend.tf, prod-aws/kafka-shared-msk/billing/__backend.tf, prod-aws/kafka-shared-msk/cbc/__backend.tf, prod-aws/kafka-shared-msk/contact-channels/__backend.tf, prod-aws/kafka-shared-msk/customer-billing/__backend.tf, prod-aws/kafka-shared-msk/customer-proposition/__backend.tf, prod-aws/kafka-shared-msk/customer-support/__backend.tf, prod-aws/kafka-shared-msk/data-infra/__backend.tf, prod-aws/kafka-shared-msk/energy-budget-plan/__backend.tf, prod-aws/kafka-shared-msk/iam/__backend.tf, prod-aws/kafka-shared-msk/payment-platform/__backend.tf, prod-aws/kafka-shared-msk/pubsub/__backend.tf, prod-aws/kafka-shared-msk/workplace-infrastructure/__backend.tf
Set the backend definition directly in the modules
Until now, the backend was defined in the terraform applier CRD. 
These are removed in this PR : https://github.com/utilitywarehouse/kubernetes-manifests/pull/97424
=> DENA-968: prod: Added backend config for msk modules

.tflint-msk.hcl, dev-aws/kafka-shared-msk/pubsub/__backend.tf
This includes checking the backend definition in the modules:
https://github.com/utilitywarehouse/tflint-ruleset-kafka-config?tab=readme-ov-file#rules
=> DENA-969: Add the uw-kakfa-config plugin to the MSK config

.pre-commit-config.yaml
So one can specify just this hook when invoking `pre-commit`, e.g. like:
pre-commit run --all-files terraform_tflint_msk
So one can run that hook without running the other `tflint` hook over the hosted team configs. This is mostly useful while debugging our internal plugin used with that hook
[1] https://pre-commit.com/#config-alias
=> Add alias for MSK `tflint` hook

dev-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/account.tf
We're going to  moving our idv projector to consume from msk rather than the A&I proximo, these  certs should allow that in dev and prod.
=> Cs 1739  make certs for crm idv to account

dev-aws/kafka-shared-msk/customer-billing/modules.tf, dev-aws/kafka-shared-msk/customer-billing/topics.tf, prod-aws/kafka-shared-msk/customer-billing/modules.tf, prod-aws/kafka-shared-msk/customer-billing/topics.tf
- Old one will be discontinued after k8s manifests changes.
- rename retry consumer groups to be more consistent.
=> [BEX-1073] - Create new DQL with different name and retention.

dev-aws/kafka-shared-msk/account-identity/account.tf, dev-aws/kafka-shared-msk/cbc/cbc.tf, dev-aws/kafka-shared-msk/iam/iam.tf
So that teams have control over who produces to/consumes from their
topics. This follows on from 859c8b716d44e65733498b8cd67ba63f9304e9e8.
There should be no conflicting resources here, but we'll have to be
careful about applying to avoid deleting any existing ACLs, the plan is:
* `terraform state rm` in the module from which we removed the ACLs, so
terraform no longer tracks them there
* `terraform apply` in the module we added the ACLs to, this should be a
no-op as Terraform should detect the ACLs already exist and just add
them to the state
Ticket: DENA-994
=> Move existing `tls-apps` to the same module as their topics

.tflint-msk.hcl, prod-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/legacy_account.tf, prod-aws/kafka-shared-msk/cbc/cbc.tf, prod-aws/kafka-shared-msk/iam/iam.tf
- Move `tls-app`'s to modules they consume/produce on
This is the same thing as cd7c0f097ab7fc6cedd48a93a70a9ccae27ee7e2 but
for prod. This charge similarly needs some manually `terraform apply`ing
before merge to avoid potential deleting ACLs
- Enable MSK topic checking tflint pluin rule
With the previous commit, there should be no offending modules in this
repo, so enable the rule to keep it that way.
Ticket:  DENA-994
=> Move `tls-app`'s to modules they consume/produce on

prod-aws/kafka-shared-msk/account-identity/exceptions.tf, prod-aws/kafka-shared-msk/account-identity/holders.tf, prod-aws/kafka-shared-msk/account-identity/legacy_account.tf
See ticket for explanations: https://linear.app/utilitywarehouse/issue/DENA-991/kafka-config-validate-tls-app-cert-common-name-is-unique-in-a-module
For safety, before applying, I'll remove from the state the ones that are set to be destroyed
=> DENA-991: prod account-identity: have a single tls-app module per cert-common-name

prod-aws/kafka-shared-msk/workplace-infrastructure/netapp-audit.tf
See ticket for explanations: https://linear.app/utilitywarehouse/issue/DENA-991/kafka-config-validate-tls-app-cert-common-name-is-unique-in-a-module
For safety, before applying, I'll remove from the state the ones that are set to be destroyed
=> DENA-991: workplace-infrastructure: have a single tls-app module per cert-common-name

dev-aws/kafka-shared-msk/account-identity/account.tf
This was picked up by the validation rule that I'm currently working on.
=> DENA-671: Enable remote storage for account-identity.public.account.events in dev

dev-aws/kafka-shared-msk/account-identity/account.tf, dev-aws/kafka-shared-msk/account-identity/exceptions.tf, dev-aws/kafka-shared-msk/account-identity/finance.tf, dev-aws/kafka-shared-msk/account-identity/holders.tf, dev-aws/kafka-shared-msk/account-identity/legacy_account.tf
Retention time is irrelevant for compacted topics.
See https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#retention-ms
=> DENA-671: dev: Remove retention time from compacted topics

prod-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/exceptions.tf, prod-aws/kafka-shared-msk/account-identity/finance.tf, prod-aws/kafka-shared-msk/account-identity/holders.tf, prod-aws/kafka-shared-msk/account-identity/legacy_account.tf
Retention time is irrelevant for compacted topics.
See https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#retention-ms
=> DENA-671: prod: Remove retention time from compacted topics

.tflint-msk.hcl
Using the latest release: https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.8.0 that brings in comments validations for millis properties
=> DENA-671: Update to latest plugin version: include comments validations

dev-aws/kafka-shared-msk/customer-proposition/customer-proposition.tf
These were added since I created the [initial unification PR,](https://github.com/utilitywarehouse/kafka-cluster-config/pull/678) so fixing them too
=> DENA-671: Unify comments for bytes properties

.semgrep/rules.yaml, .tflint-msk.hcl
To bring in the latest release[1]. Also make the new rule non-ignorable,
since there's no good reason to not prefix the consumer group names
Link: https://github.com/utilitywarehouse/tflint-ruleset-kafka-config/releases/tag/v1.10.0 [1]
=> Bump our `tflint` plugin

prod-aws/kafka-shared-msk/pubsub/mirror-maker.tf
Context: cbc is mirroring a big topic and this drives the CPU high in MSK https://grafana.prod.aws.uw.systems/d/rrE2HgHVz/msk-kafka-metrics?orgId=1&refresh=30s
=> Put quota in place for Mirror Maker as it drives the CPU high

dev-aws/kafka-shared-msk/cbc/cbc.tf
Reverts utilitywarehouse/kafka-cluster-config#705
=> Revert "dev/cbc: remove customer-api lifecycle permissions for metric test"

dev-aws/kafka-shared-msk/customer-billing/modules.tf, dev-aws/kafka-shared-msk/customer-billing/topics.tf
context - https://github.com/utilitywarehouse/kubernetes-manifests/pull/99563
=> add bex fulfilment large invoice topics to dev

dev-aws/kafka-shared-msk/pubsub/pubsub-test-throughput.tf
And match the number of partitions between the source and producing target. We want to experiment with a best-case concurrent setup
=> Bump partitions for throughput example

dev-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/account.tf
In preparation for https://github.com/utilitywarehouse/kubernetes-manifests/pull/101478
=> account-identity: Add business validation projector consumer

dev-aws/otel/otel.tf
The new tail sampler will:
* Read from the current `otel.otlp_spans` topic
* Produce to the new `otel.otlp_sampled_spans`
Later `tempo` will also be configure to read from the new topic and not the old one, but we'll leave it alone for now.
Ticket: DENA-1126
=> Add topic and app for new otel collector

dev-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/account.tf
some [slack context](https://utilitywarehouse.slack.com/archives/C0337K04DTP/p1734085584032149)
=> msk/account-identity: Add moved block to properly fix typo

dev-aws/otel/otel.tf
=> Add missing consumer group for sampling collector

dev-aws/otel/otel.tf, prod-aws/otel/otel.tf
Using a separate producer for the web collectors
=> DENA-933 - add producer for web collectors

dev-aws/otel/otel.tf
=> Allow Tempo reads from sampled spans topic

prod-aws/otel/otel.tf
I.e. bring in equivalent changes as:
* 94b5f07e8f51316ffcebe0d2ba54c6b7e0f51af7
* e6749aef789070d22466dd830466bfc2bab3f660
* 0b607e7cf9fef84753364c30f347f7c6f51b9abd
Ticket: DENA-1126
=> Bring dev changes for Otel to prod

dev-aws/kafka-shared-msk/account-identity/account.tf, prod-aws/kafka-shared-msk/account-identity/account.tf
Consumer introduced in [this PR](https://github.com/utilitywarehouse/account-platform/pull/1540)
=> msk/account-identity: Add acc api v2 email verifier consumer

dev-aws/kafka-shared-msk/account-identity/kafka-connect.tf, dev-aws/kafka-shared-msk/customer-proposition/kafka-connect.tf, dev-aws/kafka-shared-msk/dev-enablement/kafka-connect.tf
Using kafka connect to consume from particular topics
* `customer-proposition.service-status.events.v3` - for account to service(s) mapping
* `account-identity.legacy.account.events` - for denormalising the account model
=> chore: DENA-424 - add config for kafka connect

dev-aws/otel/otel.tf
I keep using GoC (Grafana on Call) when I mean to be referring to Grafana Cloud (gc)
Ticket: DENA-1238
=> Rename Grafana Cloud collector app

dev-aws/otel/otel.tf, prod-aws/otel/otel.tf
We're no longer using the additional collector, so drop these Kafka resources. This reverts commits
* 76ff931e9ea2c4b4d4e2cf8b7042b873e60d99e5.
* 4541a2992e84633f3d02f3292ca30eca4b30ddab
* 6454ecce0c4fa7e1d11a3375ca7147a06e7d506c
Ticket: DENA-1117
=> Revert "Add app for OTEL GoC collector"

prod-aws/kafka-shared-msk/energy-platform/energy-platform.tf
This consumer group has different id in prod and in dev. Correcting the prod one.
=> [EXP-952] correct consumer group id

dev-aws/kafka-shared-msk/dev-enablement/kafka-connect.tf
Use another consumer group for backing up as parquet
=> Allow another consumer group for parquet backup

dev-aws/kafka-shared-msk/dev-enablement/kafka-connect.tf
Both topics should be safe to recreate:
- dev-enablement.connect-offsets: these hold only offsets from Sources, and we don't have any atm -- I used some for testing S3 restores
- dev-enablement.connect-status: these hold the topic status -> the messages should be recreated once we restart the connector
=> Reduce the number of partitions, as we're not running a big kafka-connect cluster

dev-aws/kafka-shared-msk/energy-platform/energy-platform.tf
I want to test elasticsearch index lifecycle management 
Plan is to have this new consumer consuming meter reads and indexing them in a new index alias created in elastic, that follows the rollover policy
=> add a new consumer group

dev-aws/kafka-shared-msk/customer-support/vulnerability.tf
Adds Kafka client certificate config for access to product to the Vulnerability topic. This is for the Origin customer importer.
=> [dev/customer-support] Add origin importer certificate config

prod-aws/kafka-shared-msk/customer-billing/modules.tf
allows mail-sender dlq job to feed messages back into the topic that mail sender consumes from, to allow this dlq job to work - https://github.com/utilitywarehouse/kubernetes-manifests/pull/108711
=> add invoice-fulfilment topic to mail sender dlq produce topics

dev-aws/kafka-shared-msk/energy-platform/gentrack.tf
This PR adds new kafka topic - energy-platform.gentrack.migration.events topic. It will be used to pass migration specific events to the gentrack-migration service
=> new gentrack related kafka topic created

dev-aws/kafka-shared-msk/energy-platform/gentrack.tf
The name of the consumer is different than I initially assumed
=> update cert_common_name for gentrack migration module

dev-aws/kafka-shared-msk/energy-platform/gentrack.tf
- allow benthos energy billing sqs-processor to produce to billing events topic.
- we receive billing blobs in an S3 bucket then we get an SQS queue notification which we use benthos to bridge the SQS messages > kafka.
=> feat: allow benthos sqs queue processor to produce

dev-aws/kafka-shared-msk/energy-platform/meter-reads.tf, prod-aws/kafka-shared-msk/energy-platform/meter-reads.tf
- Allow the projector to access market interactions
- Keep prod aligned (It's currently disabled in prod)
=> Add meter-reads-api-projector to Gentrack Topics

dev-aws/kafka-shared-msk/msk-backup-bucket-retention/__backend.tf
Without this the TF applier gets an error.
=> Add AWS region to AWS provider
